package io.github.andresviedma.tinytuya.network

import io.github.andresviedma.tinytuya.crypto.TuyaCipher
import io.github.andresviedma.tinytuya.protocol.ByteUtils.hexToBytes
import io.github.andresviedma.tinytuya.protocol.ByteUtils.macSha256
import io.github.andresviedma.tinytuya.protocol.ByteUtils.toHexString
import io.github.andresviedma.tinytuya.protocol.TuyaProtocolVersion
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith

/**
 * End-to-end simulation of the Tuya v3.4 / v3.5 three-way session key handshake,
 * exercising SessionKeyNegotiation without any network I/O.
 *
 * Handshake summary:
 *   Step 1 — client sends clientNonce (16 bytes)
 *   Step 2 — device replies with AES-ECB(realKey, deviceNonce || HMAC(realKey, clientNonce))
 *   Step 3 — client replies with HMAC(realKey, deviceNonce)
 *   Finalize — session key = f(clientNonce XOR deviceNonce, realKey, version)
 *
 * All vectors cross-verified against the Python tinytuya reference implementation.
 */
class TuyaConnectionSessionKeyTest {

    private val localKey    = "JvEuI)cyLCdpGFf:"
    private val realCipher  = TuyaCipher(localKey)

    // Fixed nonces — same as used in XenonDevice tests ("not-so-random" fixture from Python)
    private val clientNonce = "30313233343536373839616263646566".hexToBytes()  // b"0123456789abcdef"
    private val deviceNonce = "61626364656630313233343536373839".hexToBytes()  // b"abcdef0123456789"

    // Device step-2 payload: AES-ECB(realKey, deviceNonce(16) + HMAC(realKey,clientNonce)(32))
    // Generated by Python: cipher.encrypt(deviceNonce + hmac.new(localKey, clientNonce, sha256).digest(), use_base64=False)
    private val step2Encrypted = (
        "5b4a2faa852004bf2bf5047202f11111025e47725b6213cce72f220c81e5a4d3" +
        "8216608c26bc3fad4c2f065b7979c44411e6ac7806d5759a3b5da8a05da8b85d"
    ).hexToBytes()

    // ----------------------------------------------------------------
    // parseStep2
    // ----------------------------------------------------------------

    @Test
    fun testParseStep2V34ExtractsDeviceNonce() {
        val extracted = SessionKeyNegotiation.parseStep2(
            step2Payload = step2Encrypted,
            realCipher   = realCipher,
            clientNonce  = clientNonce,
            version      = TuyaProtocolVersion.V3_4,
        )
        assertContentEquals(deviceNonce, extracted, "extracted device nonce")
    }

    @Test
    fun testParseStep2V35UsesPlaintext() {
        // v3.5: payload arrives unencrypted (GCM on the outer frame handles integrity)
        val step2Plain = deviceNonce + clientNonce.macSha256(realCipher.keyBytes)
        val extracted = SessionKeyNegotiation.parseStep2(
            step2Payload = step2Plain,
            realCipher   = realCipher,
            clientNonce  = clientNonce,
            version      = TuyaProtocolVersion.V3_5,
        )
        assertContentEquals(deviceNonce, extracted, "extracted device nonce")
    }

    @Test
    fun testParseStep2RejectsWrongHmac() {
        // Corrupt the embedded HMAC — parseStep2 must throw
        val tampered = step2Encrypted.copyOf().also { bytes ->
            // Flip a byte deep in the payload (after the deviceNonce block)
            val plain  = realCipher.decrypt(bytes)
            plain[20]  = (plain[20].toInt() xor 0xff).toByte()
            val corrupt = realCipher.encrypt(plain)
            corrupt.copyInto(bytes)
        }
        assertFailsWith<IllegalArgumentException>("HMAC check") {
            SessionKeyNegotiation.parseStep2(
                step2Payload = tampered,
                realCipher   = realCipher,
                clientNonce  = clientNonce,
                version      = TuyaProtocolVersion.V3_4,
            )
        }
    }

    // ----------------------------------------------------------------
    // buildStep3
    // ----------------------------------------------------------------

    @Test
    fun testBuildStep3ProducesCorrectHmac() {
        // Python: hmac.new(localKey, deviceNonce, sha256).digest()
        val step3 = SessionKeyNegotiation.buildStep3(deviceNonce, realCipher)
        assertEquals(
            "2f9c07bb840c020193e8cd18deadf37e3fc102f48c389ba1dd1f33ce52b3a8e9",
            step3.toHexString()
        )
        assertEquals(32, step3.size)
    }

    // ----------------------------------------------------------------
    // deriveSessionKey
    // ----------------------------------------------------------------

    @Test
    fun testDeriveSessionKeyV34() {
        val sessionKey = SessionKeyNegotiation.deriveSessionKey(
            clientNonce = clientNonce,
            deviceNonce = deviceNonce,
            realCipher  = realCipher,
            version     = TuyaProtocolVersion.V3_4,
        )
        assertEquals("74a78f53509872490e78048a8c6c45f2", sessionKey.toHexString())
        assertEquals(16, sessionKey.size)
    }

    @Test
    fun testDeriveSessionKeyV35() {
        val sessionKey = SessionKeyNegotiation.deriveSessionKey(
            clientNonce = clientNonce,
            deviceNonce = deviceNonce,
            realCipher  = realCipher,
            version     = TuyaProtocolVersion.V3_5,
        )
        assertEquals("864a1aee47bc070f79ecc471e1c1ec1c", sessionKey.toHexString())
        assertEquals(16, sessionKey.size)
    }

    // ----------------------------------------------------------------
    // Full handshake simulation (v3.4)
    // ----------------------------------------------------------------

    @Test
    fun testFullHandshakeV34() {
        // --- Step 1: client generates nonce (fixed for determinism) ---
        val step1Payload = clientNonce
        assertEquals("30313233343536373839616263646566", step1Payload.toHexString())

        // --- Step 2: client parses device response ---
        val extractedDeviceNonce = SessionKeyNegotiation.parseStep2(
            step2Payload = step2Encrypted,
            realCipher   = realCipher,
            clientNonce  = clientNonce,
            version      = TuyaProtocolVersion.V3_4,
        )
        assertContentEquals(deviceNonce, extractedDeviceNonce)

        // --- Step 3: client builds finish payload ---
        val step3Payload = SessionKeyNegotiation.buildStep3(extractedDeviceNonce, realCipher)
        assertEquals(
            "2f9c07bb840c020193e8cd18deadf37e3fc102f48c389ba1dd1f33ce52b3a8e9",
            step3Payload.toHexString()
        )

        // --- Finalize: derive session key ---
        val sessionKey = SessionKeyNegotiation.deriveSessionKey(
            clientNonce = clientNonce,
            deviceNonce = extractedDeviceNonce,
            realCipher  = realCipher,
            version     = TuyaProtocolVersion.V3_4,
        )
        assertEquals("74a78f53509872490e78048a8c6c45f2", sessionKey.toHexString())

        // --- Verify session key can be used as a cipher ---
        val sessionCipher = TuyaCipher(sessionKey)
        val json          = """{"dps":{"1":true}}"""
        val encrypted     = sessionCipher.encrypt(json.toByteArray())
        val decrypted     = sessionCipher.decrypt(encrypted).toString(Charsets.UTF_8)
        assertEquals(json, decrypted)
    }

    @Test
    fun testFullHandshakeV35() {
        // v3.5 step-2 payload arrives as plaintext
        val step2Plain = deviceNonce + clientNonce.macSha256(realCipher.keyBytes)

        val extractedDeviceNonce = SessionKeyNegotiation.parseStep2(
            step2Payload = step2Plain,
            realCipher   = realCipher,
            clientNonce  = clientNonce,
            version      = TuyaProtocolVersion.V3_5,
        )
        assertContentEquals(deviceNonce, extractedDeviceNonce)

        val step3Payload = SessionKeyNegotiation.buildStep3(extractedDeviceNonce, realCipher)
        assertEquals(
            "2f9c07bb840c020193e8cd18deadf37e3fc102f48c389ba1dd1f33ce52b3a8e9",
            step3Payload.toHexString()
        )

        val sessionKey = SessionKeyNegotiation.deriveSessionKey(
            clientNonce = clientNonce,
            deviceNonce = extractedDeviceNonce,
            realCipher  = realCipher,
            version     = TuyaProtocolVersion.V3_5,
        )
        assertEquals("864a1aee47bc070f79ecc471e1c1ec1c", sessionKey.toHexString())
    }
}
